name: glucolives
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  simple_animations: ^1.3.4
  google_fonts: ^0.3.3
  firebase_auth: ^0.16.0
  splashscreen: ^1.2.0
  flutter_signin_button: ^1.0.0
  firebase_messaging: ^6.0.13
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.12.9+5
  flutter_auth_buttons: ^0.8.0
  google_sign_in: ^4.4.4
  auto_size_text: ^2.1.0
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.17.4
  giffy_dialog: ^1.7.0
  charts_flutter: ^0.9.0
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  curved_navigation_bar: ^0.3.1
  flutter_snake_navigationbar: ^0.3.0
  flutter_screenutil: ^1.0.2
  responsive: ^0.2.3+4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/plate1.png
    - assets/images/logo.png
    - assets/images/food.png
    - assets/images/brain.png
    - assets/images/grafik.png
    - assets/images/sugar.png
    - assets/images/aksam.png
    - assets/images/ogle.png
    - assets/images/sabah.png
    - assets/images/gece.png
    - assets/images/insulin.png
    - assets/images/google.png
    - assets/images/basarili-min.gif
    - assets/images/diyabet.png
    - assets/icons/
    - assets/images/insulin2.png
    - assets/images/logo3.png
    - assets/images/aa.png
    - assets/images/aaa.png
    - assets/images/aaaa.png
    - assets/images/ab.png
    - assets/images/sekergif.gif
    - assets/images/source.gif
    - assets/images/besinsecimi.gif
    - assets/images/plate2.png
    - assets/images/plate6.png
    - assets/images/fruit.png
    - assets/images/BiberDolmasi.png
    - assets/images/makarna.png
    - assets/images/domatescorbasi.png
    - assets/images/kırmızımercimek.png
    - assets/images/yesilmercimek.png
    - assets/images/tavukcorbasi.png
    - assets/images/Kurufasulye.png
    - assets/images/pilav.png
    - assets/images/elma.png
    - assets/images/karpuz.png
    - assets/images/ekmek.png
    - assets/images/tambugday.png
    - assets/images/ekmek2.png
    - assets/images/baklava.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/Montserrat-SemiBold.ttf
        - asset: assets/Montserrat-SemiBoldItalic.ttf
          style: italic
    - family: FlutterIcons
      fonts:
        - asset: assets/FlutterIcons.ttf
    - family: Quicksand
      fonts:
        - asset: assets/Quicksand-Medium.ttf
        - asset: assets/Quicksand-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
